version: 2

sources:
    - name: raw
      #For bigquery:
      database: "{{ env_var('GCLOUD_PROJECT_NAME') }}"
      schema: raw
      tables:
        - name: external_departure
        - name: external_arrival
        - name: airlines
        - name: airports
        - name: cities
        - name: routes


models:
  - name: stg_arrivals
    description: Flights arriving to chosen Airport
    columns:
      - name: flight_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: icao24
        description: Unique ICAO 24-bit address of the transponder in hex string representation. All letters are lower case.
      - name: first_seen
        description: Estimated time of departure for the flight as Unix time (seconds since epoch). 
      - name: dep_airport
        description: ICAO code of the estimated departure airport. Can be null if the airport could not be identified. 
      - name: last_seen
        description: Estimated time of arrival for the flight as Unix time (seconds since epoch) 
      - name: arr_airport
        description: 	ICAO code of the estimated arrival airport. Can be null if the airport could not be identified. 
      - name: callsign
        description: >
            Callsign of the vehicle (8 chars). Can be null if no callsign has been received. 
            If the vehicle transmits multiple callsigns during the flight, we take the one seen most frequently 
      - name: dep_airport_horiz_distance
        description: Horizontal distance of the last received airborne position to the estimated departure airport in meters
      - name: dep_airport_vert_distance
        description: Vertical distance of the last received airborne position to the estimated departure airport in meters
      - name: arr_airport_horiz_distance
        description: Horizontal distance of the last received airborne position to the estimated arrival airport in meters
      - name: arr_airport_vert_distance
        description: Vertical distance of the last received airborne position to the estimated arrival airport in meters
      
  - name: stg_departures
    description: Flights departing from chosen Airport
    columns:
      - name: flight_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: icao24
        description: Unique ICAO 24-bit address of the transponder in hex string representation. All letters are lower case.
      - name: first_seen
        description: Estimated time of departure for the flight as Unix time (seconds since epoch). 
      - name: dep_airport
        description: ICAO code of the estimated departure airport. Can be null if the airport could not be identified. 
      - name: last_seen
        description: Estimated time of arrival for the flight as Unix time (seconds since epoch) 
      - name: arr_airport
        description: 	ICAO code of the estimated arrival airport. Can be null if the airport could not be identified. 
      - name: callsign
        description: >
            Callsign of the vehicle (8 chars). Can be null if no callsign has been received. 
            If the vehicle transmits multiple callsigns during the flight, we take the one seen most frequently 
      - name: dep_airport_horiz_distance
        description: Horizontal distance of the last received airborne position to the estimated departure airport in meters
      - name: dep_airport_vert_distance
        description: Vertical distance of the last received airborne position to the estimated departure airport in meters
      - name: arr_airport_horiz_distance
        description: Horizontal distance of the last received airborne position to the estimated arrival airport in meters
      - name: arr_airport_vert_distance
        description: Vertical distance of the last received airborne position to the estimated arrival airport in meters

  # - name: stg_airlines
  # - name: stg_airports
  # - name: stg_routes
  
  #       tests:
  #         - accepted_values:
  #             values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']