version: 2


models:
  - name: fact_flights
    description: Main Flights data!
    columns:
      - name: flight_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: icao24
        description: Unique ICAO 24-bit address of the transponder in hex string representation. All letters are lower case.
      - name: first_seen
        description: Estimated time of departure for the flight as Unix time (seconds since epoch). 
      - name: dep_airport
        description: ICAO code of the estimated departure airport. Can be null if the airport could not be identified. 
      - name: last_seen
        description: Estimated time of arrival for the flight as Unix time (seconds since epoch) 
      - name: arr_airport
        description: 	ICAO code of the estimated arrival airport. Can be null if the airport could not be identified. 
      - name: callsign
        description: >
            Callsign of the vehicle (8 chars). Can be null if no callsign has been received. 
            If the vehicle transmits multiple callsigns during the flight, we take the one seen most frequently 
      - name: dep_airport_horiz_distance
        description: Horizontal distance of the last received airborne position to the estimated departure airport in meters
      - name: dep_airport_vert_distance
        description: Vertical distance of the last received airborne position to the estimated departure airport in meters
      - name: arr_airport_horiz_distance
        description: Horizontal distance of the last received airborne position to the estimated arrival airport in meters
      - name: arr_airport_vert_distance
        description: Vertical distance of the last received airborne position to the estimated arrival airport in meters
      - name: flight_type
        description: Vertical distance of the last received airborne position to the estimated arrival airport in meters
        tests:
          - accepted_values:
              values: ['arrival', 'departure']
      - name: airline_name
        description: Airline associated to the flight, may be Null
      - name: airline_aita
        description: AITA code of airline
      - name: airline_icao
        description: ICAO code of airline
      - name: airline_country
        description: Country of airline
      - name: dep_airport_name
        description: Name of the Departure Airport
      - name: dep_airport_city
        description: City of the Departure Airport
      - name: dep_airport_country
        description: Country of the Departure Airport
      - name: arr_airport_name
        description: Name of the Arrival Airport
      - name: arr_airport_city
        description: City of the Arrival Airport
      - name: arr_airport_country
        description: Country of the Arrival Airport

  - name: dim_daily_flights_agg
    description: Aggrigation of the flights on a daily level
  
  - name: dim_monthly_flights_agg
    description: Aggrigation of the flights on a monthly level
    
  - name: dim_monthly_country_agg
    description: Aggrigation of the countries on a monthly level
